@startuml
component "FrontEnd" as Browser

component "Backend" as Backend {
  component "Autenticação"
  component "Gerenciamento de Usuário"
  component "Gerenciamento de Vantagem"
  component "Gerenciamento de Instituição de Ensino"
  component "Gerenciamento de Moeda"
  component "Gerenciamento de Transações"
}

component "Banco de dados" as BD {
  component "Aluno"
  component "Professor"
  component "Empresa"
  component "InstituicaoEnsino"
  component "Vantagem"
  component "Transacao"
}

Browser ..> Backend : HTTPS
Backend ..> BD : ODBC
@enduml