@startuml

actor "Empresa Parceira" as parceiro
actor "Aluno" as aluno
participant "Rota" as sistema
participant "VantagemController" as controller
participant "VantagemDAO" as dao
database "Banco de Dados" as bd

ref over parceiro, aluno : Realizar login

autonumber 1
parceiro -> sistema : POST /vantagens
activate parceiro

    autonumber 1.1
    activate sistema
        sistema -> controller : criar(req, res)

        autonumber 1.1.1
        activate controller
            controller -> dao : criar(dados)

            autonumber 1.1.1.1
            activate dao
                dao -> bd : INSERT vantagem
                activate bd
                bd --> dao
                deactivate bd
            dao --> controller
            deactivate dao
        controller --> sistema
        deactivate controller
    sistema --> parceiro
    deactivate sistema
deactivate parceiro

autonumber 2
parceiro -> sistema : GET /vantagens/minhas-vantagens
activate parceiro

    autonumber 2.1
    activate sistema
        sistema -> controller : listarPorEmpresa()

        autonumber 2.1.1
        activate controller
            controller -> dao : listarPorEmpresa()

            autonumber 2.1.1.1
            activate dao
                dao -> bd : SELECT vantagens WHERE empresa_id
                activate bd
                bd --> dao
                deactivate bd
            dao --> controller
            deactivate dao
        controller --> sistema
        deactivate controller
    sistema --> parceiro
    deactivate sistema
deactivate parceiro

autonumber 3
aluno -> sistema : GET /vantagens
activate aluno

    autonumber 3.1
    activate sistema
        sistema -> controller : listarAtivas()

        autonumber 3.1.1
        activate controller
            controller -> dao : listarAtivas()

            autonumber 3.1.1.1
            activate dao
                dao -> bd : SELECT vantagens WHERE ativas
                activate bd
                bd --> dao
                deactivate bd
            dao --> controller
            deactivate dao
        controller --> sistema
        deactivate controller
    sistema --> aluno
    deactivate sistema
deactivate aluno

@enduml