@startuml

actor "Empresa Parceira" as empresa
actor "Aluno" as aluno
participant "vantagemRoutes" as rota
participant "VantagemController" as controller
participant "VantagemDAO" as dao
participant "Vantagem Model" as model
database "Banco de Dados" as bd

ref over empresa, aluno : Realizar login

empresa -> rota : 1. POST /vantagens
activate empresa 
activate rota 

alt 1.1. req.usuario.tipo != "empresa"
    rota -> controller : 1.1.1. criar(req,res)
    activate controller 
    controller -> rota 
    deactivate controller
else
    rota -> controller : 1.2.1. criar(req,res)
    activate controller 
    controller -> dao : 1.2.2. criar(dadosVantagem)
    activate dao 
        dao -> bd : 1.2.2.1. INSERT INTO vantagem …
        activate bd 
        bd  --> dao 
        deactivate bd
        dao -> dao : 1.2.2.3. buscarPorID(id)
            dao -> bd : 1.2.2.3.1. SELECT * FROM vantagem WHERE id = ?
            activate bd 
            bd  --> dao
            deactivate bd
            dao -> model : 1.2.2.3.3. new Vantagem()
            activate model 
            model --> dao
            deactivate model
        dao --> controller
    deactivate dao
    controller --> rota
    deactivate controller
end
rota --> empresa
deactivate rota
deactivate empresa

empresa -> rota : 2. GET /vantagens/minhas-vantagens
activate empresa 
activate rota 

alt 2.1. req.usuario.tipo != "empresa"
    rota -> controller : 2.1.1. listarPorEmpresa(req,res)
    activate controller 
    controller -> rota
    deactivate controller
else
    rota -> controller : 2.2.1. listarPorEmpresa(req,res)
    activate controller 
        controller -> dao : 2.2.2. listarPorEmpresa(empresa_id)
        activate dao 
            dao -> bd : 2.2.2.1. SELECT * FROM vantagem WHERE empresa_id = ?
            activate bd 
            bd  --> dao
            deactivate bd
            dao -> model : 2.2.2.3. Vantagens
            activate model 
            model --> dao
            deactivate model
        dao --> controller
        deactivate dao
    controller --> rota
    deactivate controller
end
rota --> empresa
deactivate rota
deactivate empresa

aluno -> rota : 3. GET /vantagens
activate aluno 
activate rota 

rota -> controller : 3.1. listarTodasAtivas(req,res)
activate controller
    controller -> dao : 3.1.1. listarTodasAtivas()
    activate dao 
        dao -> bd : 3.1.1.1. SELECT * FROM vantagem WHERE ativo = TRUE
        activate bd 
        bd  --> dao
        deactivate bd
        dao -> model : 3.1.1.3. Vantagens
        activate model 
        model --> dao
        deactivate model
    dao --> controller
    deactivate dao
controller --> rota
deactivate controller

rota --> aluno
deactivate rota
deactivate aluno

@enduml