```
@startuml

left to right direction
actor "Usuario" as usuario
actor "Aluno" as aluno
actor "Professor" as professor
actor "Empresa parceira" as parceiro

rectangle "Sistema de Moeda Estudantil" {
    usuario --> (Cadastrar no sistema)
    usuario --> (Entrar no sistema)

    aluno --> (Trocar moeda)
    aluno --> (Resgatar vantagem)
    aluno --> (Consultar vantagem)
    aluno --> (Consultar extrato)
    aluno <-- (Conceder moedas)
    
    professor --> (Conceder moedas)
    professor --> (Consultar extrato) 

    parceiro --> (Gerenciar vantagens)
    parceiro <-- (Resgatar vantagem)

    usuario <|-- aluno
    usuario <|-- professor
    usuario <|-- parceiro
}

@enduml
```